[tool.isort]
profile = "black"  # Align with Black formatter
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
known_third_party = ["django", "flask"]  # Specify third-party libraries
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]